# Generated by Django 2.2.13 on 2020-07-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200716_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='data',
        ),
        migrations.AddField(
            model_name='event',
            name='titulo',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='api.Agent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.User'),
        ),
    ]
