# Generated by Django 2.2.13 on 2020-07-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200717_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detalhes',
            field=models.TextField(null=True),
        ),
    ]
