# Generated by Django 2.2.13 on 2020-07-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_detalhes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='titulo',
            new_name='data',
        ),
    ]
