# Generated by Django 2.2.13 on 2020-07-18 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200718_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
    ]
